# Generated by Django 5.1 on 2024-08-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_imguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroUsuario',
        ),
        migrations.DeleteModel(
            name='ImgUser',
        ),
    ]
