# Generated by Django 5.1 on 2024-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0008_reservas_valor_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordenada",
            name="valor_hora",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservas",
            name="valor_total",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
