# Generated by Django 5.1 on 2024-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0009_coordenada_valor_hora_alter_reservas_valor_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordenada",
            name="valor_hora",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="reservas",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
