# Generated by Django 5.1 on 2024-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0011_rename_reservas_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=150)),
                ("telefone", models.IntegerField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "DadosCampo",
                "verbose_name_plural": "DadosCampos",
            },
        ),
    ]
