# Generated by Django 5.1 on 2024-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0012_dadoscampo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadoscampo",
            name="foto",
            field=models.ImageField(default="default.jpg", upload_to="camp_pics"),
        ),
    ]
