# Generated by Django 5.1 on 2024-09-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0014_alter_dadoscampo_telefone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                (
                    "avaliacoes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Estrela"),
                            (2, "2 Estrelas"),
                            (3, "3 Estrelas"),
                            (4, "4 Estrelas"),
                            (5, "5 Estrelas"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "campoAvaliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="login_app.dadoscampo",
                    ),
                ),
                (
                    "nomeUsuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario",
                        to="login_app.profile",
                    ),
                ),
            ],
        ),
    ]
