# Generated by Django 5.1 on 2024-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0015_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadoscampo",
            name="nomeCampo",
            field=models.CharField(default="Campo", max_length=50, unique=True),
        ),
    ]
