# Generated by Django 5.1 on 2024-09-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0016_dadoscampo_nomecampo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dadoscampo",
            old_name="nomeCampo",
            new_name="nome",
        ),
    ]
