# Generated by Django 5.1 on 2024-10-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0017_rename_nomecampo_dadoscampo_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="nomeUsuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
